"""SaaS Customer Retention & Regional Revenue Dashboard.

Reads CSVs from outputs/ (generated by pipeline.py) and renders four sections:
  1. Cohort retention heatmap
  2. Implied churn rate trend
  3. Regional benchmarking
  4. Monthly revenue trend (MRR proxy)

Run:
    streamlit run dashboard.py
"""

import os

import numpy as np
import pandas as pd
import plotly.express as px
import plotly.graph_objects as go
import streamlit as st

OUT_DIR = "outputs"

st.set_page_config(page_title="SaaS Retention & Revenue", layout="wide")


# --------------------------------------------------------------------------- #
# Data loading
# --------------------------------------------------------------------------- #
@st.cache_data(show_spinner=False)
def load_outputs() -> dict[str, pd.DataFrame]:
    files = {
        "cohort":   "cohort_retention.csv",
        "churn":    "churn_rate.csv",
        "regional": "regional_benchmarks.csv",
        "revenue":  "revenue_trend.csv",
        "churn_window": "churn_window.csv",
    }
    return {k: pd.read_csv(os.path.join(OUT_DIR, v)) for k, v in files.items()}


def check_outputs() -> bool:
    return all(
        os.path.exists(os.path.join(OUT_DIR, f))
        for f in ["cohort_retention.csv", "churn_rate.csv",
                  "regional_benchmarks.csv", "revenue_trend.csv"]
    )


# --------------------------------------------------------------------------- #
# App
# --------------------------------------------------------------------------- #
st.title("SaaS Customer Retention & Regional Revenue Analysis")
st.caption(
    "Cohort retention · Implied churn · Regional benchmarking · Revenue trend  |  "
    "Data: AWS SaaS Sales (Kaggle)"
)

if not check_outputs():
    st.error(
        "Output files not found. Run the pipeline first:\n\n"
        "```\npython pipeline.py\n```"
    )
    st.stop()

data = load_outputs()
churn_months = int(data["churn_window"]["churn_months"].iloc[0])

st.caption(
    f"**Churn definition:** a customer is inactive/churned if they place no order "
    f"within **{churn_months} months** of their last purchase "
    f"(= ceil(median repurchase interval × 2), derived from this dataset)."
)

# --------------------------------------------------------------------------- #
# 1. Cohort retention heatmap
# --------------------------------------------------------------------------- #
st.subheader("Cohort Retention Heatmap")
st.caption("Each row = monthly cohort by first order. Cells = % of cohort still active at month N.")

cohort = data["cohort"]
pivot = cohort.pivot(index="cohort_month", columns="month_number", values="retention_pct")
pivot.columns = [f"M{int(c)}" for c in pivot.columns]

fig_cohort = go.Figure(
    go.Heatmap(
        z=pivot.values,
        x=pivot.columns.tolist(),
        y=pivot.index.tolist(),
        colorscale="RdYlGn",
        zmin=0,
        zmax=100,
        text=np.where(np.isnan(pivot.values), "", np.round(pivot.values, 1).astype(str) + "%"),
        texttemplate="%{text}",
        colorbar=dict(title="Retention %"),
    )
)
fig_cohort.update_layout(
    margin=dict(l=10, r=10, t=30, b=10),
    height=420,
    xaxis_title="Months since first order",
    yaxis_title="Cohort (first order month)",
)
st.plotly_chart(fig_cohort, use_container_width=True)

# Auto-insight: worst retention drop
m0 = cohort[cohort["month_number"] == 0].set_index("cohort_month")["retention_pct"]
m1 = cohort[cohort["month_number"] == 1].set_index("cohort_month")["retention_pct"]
drop = (m0 - m1).dropna()
if not drop.empty:
    worst_cohort = drop.idxmax()
    st.info(
        f"**Biggest M0→M1 drop:** cohort **{worst_cohort}** lost "
        f"**{drop[worst_cohort]:.1f}%** of customers after the first month — "
        "the highest early churn across all cohorts."
    )

# --------------------------------------------------------------------------- #
# 2. Implied churn rate trend
# --------------------------------------------------------------------------- #
st.subheader("Implied Churn Rate Over Time")
st.caption(f"Monthly % of customers with no order in the past {churn_months} months.")

churn = data["churn"]
fig_churn = px.line(
    churn, x="month", y="churn_rate_pct",
    markers=True,
    labels={"month": "Month", "churn_rate_pct": "Churn rate (%)"},
)
fig_churn.update_traces(line_color="#ef553b")
fig_churn.update_layout(margin=dict(l=10, r=10, t=30, b=10), height=340)
st.plotly_chart(fig_churn, use_container_width=True)

avg_churn = churn["churn_rate_pct"].mean()
peak_churn = churn.loc[churn["churn_rate_pct"].idxmax()]
st.info(
    f"**Average monthly churn:** {avg_churn:.1f}%.  "
    f"**Peak:** {peak_churn['churn_rate_pct']:.1f}% in {peak_churn['month']}."
)

# --------------------------------------------------------------------------- #
# 3. Regional benchmarking
# --------------------------------------------------------------------------- #
st.subheader("Regional Benchmarking")

reg = data["regional"]
col1, col2 = st.columns(2)

with col1:
    st.markdown("**Revenue by region**")
    fig_rev = px.bar(
        reg.sort_values("total_revenue", ascending=True),
        x="total_revenue", y="region", orientation="h",
        labels={"total_revenue": "Total Revenue ($)", "region": "Region"},
        color="total_revenue", color_continuous_scale="Blues",
    )
    fig_rev.update_layout(
        margin=dict(l=10, r=10, t=30, b=10),
        height=340,
        coloraxis_showscale=False,
    )
    st.plotly_chart(fig_rev, use_container_width=True)

with col2:
    st.markdown("**Retention rate by region**")
    fig_ret = px.bar(
        reg.sort_values("retention_rate_pct", ascending=True),
        x="retention_rate_pct", y="region", orientation="h",
        labels={"retention_rate_pct": "Retention rate (%)", "region": "Region"},
        color="retention_rate_pct", color_continuous_scale="RdYlGn",
    )
    fig_ret.update_layout(
        margin=dict(l=10, r=10, t=30, b=10),
        height=340,
        coloraxis_showscale=False,
    )
    st.plotly_chart(fig_ret, use_container_width=True)

st.markdown("**Full regional breakdown**")
disp = reg.copy()
disp["total_revenue"] = disp["total_revenue"].map("${:,.0f}".format)
disp["avg_order_value"] = disp["avg_order_value"].map("${:,.0f}".format)
disp["retention_rate_pct"] = disp["retention_rate_pct"].map("{:.1f}%".format)
disp.columns = ["Region", "Customers", "Repeat Customers", "Retention %",
                "Total Revenue", "Avg Order Value", "Total Orders"]
st.dataframe(disp, hide_index=True, use_container_width=True)

top_region = reg.loc[reg["total_revenue"].idxmax(), "region"]
low_ret_region = reg.loc[reg["retention_rate_pct"].idxmin(), "region"]
st.info(
    f"**Top revenue region:** {top_region}.  "
    f"**Lowest retention:** {low_ret_region} — priority market for retention intervention."
)

# --------------------------------------------------------------------------- #
# 4. Revenue trend (MRR proxy)
# --------------------------------------------------------------------------- #
st.subheader("Monthly Revenue Trend (MRR Proxy)")
st.caption("Aggregate monthly sales as a proxy for MRR. Growth % = month-over-month change.")

rev = data["revenue"]
fig_trend = go.Figure()
fig_trend.add_trace(go.Scatter(
    x=rev["month"], y=rev["revenue"],
    mode="lines+markers",
    line=dict(color="#00cc96"),
    name="Revenue",
))
fig_trend.update_layout(
    margin=dict(l=10, r=10, t=30, b=10),
    height=340,
    xaxis_title="Month",
    yaxis_title="Revenue ($)",
)
st.plotly_chart(fig_trend, use_container_width=True)

rev_disp = rev.copy()
rev_disp["revenue"] = rev_disp["revenue"].map("${:,.0f}".format)
rev_disp["mom_growth_pct"] = rev_disp["mom_growth_pct"].map(
    lambda v: f"{v:+.1f}%" if pd.notna(v) else "—"
)
rev_disp.columns = ["Month", "Revenue", "Active Customers", "Orders", "MoM Growth %"]
st.dataframe(rev_disp, hide_index=True, use_container_width=True)

best_month = rev.loc[rev["revenue"].idxmax()]
st.info(
    f"**Peak revenue month:** {best_month['month']} "
    f"(${best_month['revenue']:,.0f}, {best_month['active_customers']} active customers)."
)
